spring:
  config:
    import: optional:classpath:.env[.properties]
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DOCKER_DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
#    defer-datasource-initialization: true

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${KC_CLIENT_ID}
            authorization-grant-type: authorization_code
            scope: openid

        provider:
          keycloak:
            issuer-uri: ${DOCKER_KC_ISSUER_URI}
            user-name-attribute: preferred_username

      resourceserver:
        jwt:
          issuer-uri: ${DOCKER_KC_ISSUER_URI}

cloudinary:
  cloud_name: ${CLOUD_NAME}
  api_key: ${CLOUD_API_KEY}
  api_secret: ${CLOUD_API_SECRET}

server:
  port: 8081
